### PR TITLE
Moar options: REST format, custom headers

### LINKED ISSUE #10: Custom (and default?) headers
An important use case for us at @FiftyThree is to pass custom headers in the underlying requests. (And they vary across requests, so it's not just a static default.)

Examples of how we use those:

- **User-Agent**. The Neo4j team encourages drivers to set this (to `driver/version`), btw, so cypher-stream should do this by default I think (e.g. `cypher-stream/0.2.1`), but we're also thinking of expanding this to include our app's name, since we'll soon be having two apps talking to the same Neo4j database. (That'll let us differentiate and understand our load across the two.)

- **Tracing**. We send along a header with an ID for the outermost "app-level" request, so we can both visualize all the database requests that made up an app requests, and debug failed app requests. This is a common technique, e.g. [Twitter's Zipkin](http://twitter.github.io/zipkin/) (what we use), [Heroku's X-Request-ID](https://brandur.org/request-ids), etc.

- **Query names**. We want to be able to analyze the performance of our queries, but using the full query body would be untenable. So we send along a X-Query-Name header with every query that's a short, human-readable name for this query (e.g. `User_getByEmail`), which we then log. E.g.:

Example screenshot of the last case:

home-stream-perf-queries

So it'd be really valuable to be able to pass custom headers along to Cypher requests.

WDYT of supporting these alternate signature then?

```js
var cypher = require('cypher-stream')({
    url: 'http://localhost:7474',
    headers: {...}  // default headers, if you want to set any; e.g. User-Agent
});

cypher({
    query: 'match (user:User {email: {email}}) return user',
    params: {email: 'foo@example.com'},
    headers: {...}  // e.g. X-Query-Name
})
  .on('data', function (result){
    console.log(result.user.first_name);
  })
  .on('end', function() {
    console.log('all done');
  })
;
```

### LINKED ISSUE #13: Support for REST format
Quick bug first: `extractData` [recursively calls itself](https://github.com/brian-gates/cypher-stream/blob/4e121f0cc73aba6161dc0c92daf942cc9cda5f52/CypherStream.js#L15-L17) if an object has a `data` property, so this means it'll incorrectly drop legitimate property data if there happens to be a property named `data`. =)

But wait! That bug's not worth fixing, because (I *think*) you don't even need that function anymore, since the transactional endpoint returns just property data by default now. So you should just remove it.

But on that note, I'd like to request an option to return the REST format instead of the lean property-only format. Having node and relationship metadata is needed for ORM/OGM-type libraries.

Easy enough to request it:

http://neo4j.com/docs/stable/rest-api-transactional.html#rest-api-execute-statements-in-an-open-transaction-in-rest-format-for-the-return

This could potentially be just another option to add to #10's options-based API, e.g. `format`.

WDYT? SGTY? ORLY?

### PR DESCRIPTION
**Pull request by aseemk**
Fixes #10 
Fixes #13 

Simplified implementation from what I proposed in the issues in a few minor ways.

TAL and LMK if anything needs changing. Thanks!

### CODE REVIEW

**Comment by aseemk** [comment]
The tests pass for me locally, but some of the tests (all pre-existing) are timing out on Travis. Is that expected? https://travis-ci.org/brian-gates/cypher-stream/builds/48833527

**Comment by aseemk** [comment]
Checked in a `mocha.opts` file to increase the global Mocha timeout to 5 secs, up from the default of 2s (and the "slow" marker to 1s, up from 75ms), for Travis. Tests pass now. Hope that's cool?

**Comment by brian-gates** [comment]
Looks good; I've made you a contributor by the way, so feel free to continue development as needed :)

**Comment by aseemk** [comment]
Thanks @brian-gates!

**Pull request merged**
